CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASE;

DROP TABLE CLIENTE;

/* CRIAÇÃO DE TABELAS */

CREAT TABLE CLIENTE(
    IDLCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR (30) NOT NULL,
    SEXO ENUM ('M', 'F') NOT NULL,
    EMAIL VARCHAR (50) UNIQUE,
    CPF VARCHAR (15) UNIQUE
);

CREATE TABLE ENDERECO(
    IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
    RUA VARCHAR (30) NOT NULL,
    BAIRRO VARCHAR (30) NOT NULL,
    CIDADE VARCHAR (30) NOT NULL,
    ESTADO CHAR (2) NOT NULL,
    ID_CLIENTE INT UNIQUE,

    FOREING KEY (ID_CLIENTE)
    PREFERENCES CLIENTE (IDCLIENTE)
);

CREATE TABLE TELEFONE(
    IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
    TIPO ENUM ('RES', 'COM', 'CEL') NOT NULL,
    NUMERO VARCHAR (10),
    ID_CLIENTE INT,

    FOREING KEY (ID_CLIENTE)
    PREFERENCES CLIENTE (IDCLIENTE)
);

/* ENDEREÇO - OBRIGATORIO 
CADASTRO DE SOMENTE UM.

TELEFONE - NAO OBRIGATORIO 
CADASTRO DE MAIS DE UM (OPICIONAL)

CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA 
QUE VAI ATE A OUTRA TABELA PARA FAZER REFERENCIA ENTER REGISTRO*/


/* EM RELACIONAMENTO 1 X 1 A CHAVE ESTRANGEIRA FICA NA TABELA MAIS FRACA */

/* EM RELACIONAMENTO 1 X N A CHAVE ESTRANGEIRA FICARA SEMPRE NA CARDINALIDADE N */

INSERT INTO CLIENTE VALUES (NULL, 'JOAO','M', ' JOAO@GMAIL.COM', '76567587887');
INSERT INTO CLIENTE VALUES (NULL, 'CARLOS', 'M', 'CARLOSA@GMAIL.COM', '5464553466');
INSERT INTO CLIENTE VALUES (NULL, 'ANA', 'F', 'ANA@GAMAIL.COM', '456545678' );
INSERT INTO CLIENTE VALUES (NULL, 'CLARA', 'F', NULL, '5687766856');
INSERT INTO CLIENTE VALUES (NULL, 'JEORGE', 'M', 'JEORGE@GMAIL.COM', '87565447688');
INSERT INTO CLIENTE VALUES (NULL, 'CELIA', 'M', 'JCELIA@GMAIL.COM', '576787889'),

SELECT * FROM CLIENTE;

DESC ENDERECO;

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE', 'MG', 4);
INSERT INTO ENDERECO VALUES (NULL, 'RUA CAPITAO HERMES', ' CENTRO', 'RIO DE JANEIRO', 'RJ', 1);
INSERT INTO ENDERECO VALUES (NULL, 'RUA PRES VARGAS', 'JARDINS', 'SAO PAULO', 'SP', 3);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANEGA', 'ESTACIO', 'RIO DE JANEIRO', 'RJ', 2);
INSERT INTO ENDERECO VALUES (NULL, 'RUA DO OUVIDOR', 'FLAMENGO', 'RIO DE JANEIRO', 'RJ', 6)
INSERT INTO ENDERECO VALUES (NULL, 'RUA URUGUAIANA', 'CENTRO', 'VITORIA', 'ES', 5);
INSERT INTO ENDERECO VALUES (NULL, 'RUA ALFANDEGA', 'CENTRO', 'SAO PAULO', 'SP', 5); 

SELECT * FROM ENDERECO;

DESC TELEFONE;

INSERT INTO TELEFONE VALUES (NULL, 'CEL', '78458743', 5);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '56576876', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '87866896', 1);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '54768899', 2);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '99667587', 1);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '78989765', 3);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '99766676', 3);
INSERT INTO TELEFONE VALUES (NULL, 'COM', '66687899', 1);
INSERT INTO TELEFONE VALUES (NULL, 'RES', '89986668', 5);
INSERT INTO TELEFONE VALUES (NULL, 'CEL', '88687909', 2);

SELECT * FROM TELEFONE;

/* SKECAO, PROJECAO E JUNCAO */

/* PROJECAO -> É TUDO QUE VOCE QUER NA TELA */

SELECT NOW () AS DATA_ATUAL;

SELECT 2 + 2 AS SOMA;

SELECT 2 + 2 AS SOMA, NOME, NOW ()
FROM CLIENTE;

/* SELECAO -> É UM SUBCONJUNTO DO DO CONJUNTO TOTAL DE REGISTRO DE UMA TABELA
A CLAUSULA DE SELECA E O WHERE*/

SELECT NOME, SEXO, EMAIL /* PROJECAO */ 
FROM CLIENTE /* ORIGEM */ 
WHERE TIPO = 'CEL'; /* SELECAO */

/* JUNCAO -> JOIN */

SELECT NOME, EMAIL, IDCLIENTE
FROM CLIENTE;

SELECT ID_CLIENTE, BAIRRO, CIDADE
FROM ENDERECO;

/* NOME, SEXO, BAIRRO, CIDADE */ 

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */
FROM CLIENTE, ENDERECO /* ORIGEM */
WHERE IDCLIENTE = ID_CLIENTE; /* JUNCAO */

/* WHERE = SELECAO */

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE, ENDERECO
WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F';

/* WHERE IDCLIENTE = ID_CLIENTE AND SEXO = 'F; -> TABELA VERDADE */

INSERT INTO ENDERECO VALUES (NULL, 'RUA ANTONIO SA', 'CENTRO', 'B. HORIZONTE','MG', 15);

SELECT NOME, SEXO, BAIRRO, CIDADE
FROM CLIENTE
INNER JOIN ENDERECO
ON IDCLIENTE = ID_CLIENTE

SELECT NOME, SEXO, BAIRRO, CIDADE /* PROJECAO */ 
FROM CLIENTE /* ORIGEM */ 
    INNER JOIN ENDERECO /* ORIGEM */
    ON IDCLIENTE = ID_CLIENTE /* JUNCAO */
WHERE SEXO = 'F' /* SELECAO */

/* NOME, SEXO, EMAIL, TIPO, NUMERO */

SELECT NOME, SEXO, EMAIL, TIPO, NUMERO /* PROJECAO */
FROM CLIENTE /* ORIGEM */
INNER JOIN TELEFONE /* ORIGEM */
ON IDCLIENTE = ID_CLIENTE /* JUNCAO */

/* NOME, SEXO, BAIRRO, CIDADE, TIPO, NUMERO */

SELECT CLIENTE.NOME, CLIENTE.SEXO, ENDERECO.BAIRRO, ENDERECO.CIDADE, TELEFONE.TIPO, TELEFONE.NUMERO /* PROJECAO */
FROM CLIENTE 
INNER JOIN ENDERECO
ON CLIENTE.IDCLIENTE = ENDERECO.ID_CLIENTE 
INNER JOIN TELEFONE 
ON CLIENTE.IDCLIENTE = TELEFONE.ID_CLIENTE 

SELECT C.NOME, C.SEXO, E.BAIRRO, E.CIDADE, T.TIPO, T.NUMERO 
FROM CLIENTE C 
INNER JOIN ENDERECO E 
ON C.IDCLIENTE = E.ID_CLIENTE 
INNER JOIN TELEFONE T 
ON C.IDCLIENTE = T.ID_CLIENTE

/*
	
	DML - DATA MANIPULATION LANGUAGE
	DDL - DATA DEFINITION LANGUAGE
	DCL - DATA CONTROL LANGUAGE
	TCL - TRANSACTION CONTROL LANGUAGE

*/

/* INSERT */
INSERT INTO CLIENTE VALUES (NULL, 'PAULA','F',NULL, '77437493');
INSERT INTO CLIENTE VALUES (NULL, 'RUA JOAQUIM SILVA', 'ALVORADA', 'NITERIO', 'RJ', 7);


SELECT * FROM CLIENTE;

/* FILTRO */

SELECT * FROM CLIENTE
WHERE SEXO = 'M';

/*UPDATE */

SELECT * FROM CLIENTE;
WHERE IDCLIENTE = 7;

UPDATE CLIENTE
SET SEXO = 'F'
WHERE IDCLIENTE = 7;

/* DELETE */

INSERT INTO CLIENTE VALUES (NULL, 'XXX','M',NULL, 'XXX');

SELECT * FROM CLIENTE; 
WHERE IDCLIENTE = 8;

DELETE FROM CLIENTE
WHERE IDCLIENTE = 8;

/* DLL - DATA DEFINITION LANGUAGE */

CREATE TABLE PRODUTO(
    IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PRODUTO VARCHAR (30) NOT NULL,
    PRECO_INT,
    FRETE FLOAT (10,2) NOT NULL,
);

/* ALTER TABLE  */

/* ALTERANDO O NOME DE UMA COLUNA - CHANGE */

ALTER TABLE CLIENTE
CHANGE PRECO VALOR_UNITARIO INT NOT NULL;

DESC PRODUTO;

/* MODIFY - ALTERANDO O TIPO */

ALTER TABLE PRODUTO
MODIFY VALOR_UNITARIO VARCHAR (50) NOT NULL;

/* ADD - ADICIONANDO UMA COLUNA */

ALTER TABLE PRODUTO
ADD PESO FLOAT (10,2) NOT NULL;

/* APAGANDO UMA COLUNA */

ALTER TABLE PRODUTO
DROP COLUMN PESO;

/*ADICIONANDO UMA COLUNA NA ORDEM ESPECIFICA */

ALTER TABLE PRODUTO
ADD COLUMN PESO FLOAT (10,2) NOT NULL;
AFTER NOME_PRODUTO;

ALTER TABLE PRODUTO
DROP COLUMN PESO;

AFTER TABLE PRODUTO
ADD COLUMN PESO FLOAT (10,2) NOT NULL
FIRST;