/* FORMA 01 - OMITINDO AS COLUNAS */ 
INSERT INTO CLINETE VALUES ('CHRISTIAN','M','CHRISTIANMICAEL07@gmail.com',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');

INSERT INTO CLINETE VALUES ('CELIA','F','CELIA@gmail.com', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');

INSENSITIVE INTO CLINETE VALUES ('JORGE','M',NULL, 885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');

/* FORMA 02 - COLOCANDO AS COLUNAS */

INSERT INTO CLINETE (NOME, SEXO, EMAIL, TELEFONE, CPF, ENDERECO) VALUES ('LILIAN','F','SENADOR SOARES -TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */

INSERT INTO CLINETE VALUES ('ANA','F','ANA@globo.com', 85548962, '54556985', 'PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
('CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR
SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999999);
INSERT INTO CLIENTE(NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES('CLARA','F','SENADOR
SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222222);

/* O COMANDO SELECT: Seleção, Projeção e Junção. */
SELECT NOW() as DATA_HORA, 'JOÃO MARCOS' AS PROFESSOR;
SELECT 'JOÃO';
SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */
SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;
SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME FROM CLIENTE;
SELECT EMAIL, SEXO, ENDERECO, NOME, NOW() AS DATA_HORA FROM CLIENTE;
SELECT * FROM CLIENTE;

/* 1 - RETORNANDO DADOS COM O COMANDO SELECT*/
SELECT NOME, TELEFONE FROM CLIENTE;

/* 2 - FILTRANDO DADOS UTILIZANDO OS COMANDOS WHERE*/
SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';
SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';
SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';